### ISSUE TITLE
Sample for downloading an attachment?

### ISSUE THREAD

**Issue by saibotsivad** [fastmail/JMAP-Samples#18]
I've been reading through the JMAP specs and the Fastmail docs, and I can't figure out how to use JMAP to fetch an individual attachment from an email.

* Is this even possible? I can use other methods to get the attachment bytes, but it has all the other metadata (mime-type, name, blob id, etc) so that it feels like it should be right there.
* If it's possible, can it be added to this repo as an example? (I could make a PR once I understand it.)
* If it's not possible, is there a related Fastmail API that I could use instead?

**Comment by rjbs** [comment]
@saibotsivad This is a very drive-by comment because I saw this just before I closed my laptop.  You want to use JMAP downloads, using the download URI in the session object, to download the blob identified in the email's attachments property.

If this isn't a helpful comment (sorry, might not be!) I will post some code tomorrow.  For now, closing my lid and reading a book.  Good luck!

**Comment by rjbs** [comment]
@saibotsivad  Okay, sorry, this is a few days longer than I said!

I took the top-ten program, using perl5, because it's fastest for me.  Same as every other language, it does a chained Email/query and Email/get.  Let's say that we want to print the full bytes of the first attachment to a message that has one.

First, I send my test account an email with a plaintext attachment! 🙂

I run the program, and…

```
snowdrop:~/fm/code/JMAP-Samples/perl5$ perl top-ten
2022-10-02T20:11:59Z - This has an attachment!
2022-08-01T19:29:21Z - Get the most out of Fastmail
2022-08-01T19:29:21Z - Protecting your account
2022-08-01T19:29:18Z - Welcome to Fastmail
```

Great.  Now let's get the attachment.  I add `attachments` to the properties fetched and pretty-print the data structure.  I get this:

```
'attachments' => [
                   {
                     'language' => undef,
                     'blobId' => 'Gc178fb8e816b892993bccce236c358a3d2c8b9d0',
                     'location' => undef,
                     'name' => 'top-ten',
                     'charset' => undef,
                     'partId' => '2',
                     'cid' => undef,
                     'size' => 1945,
                     'disposition' => 'attachment',
                     'type' => 'application/octet-stream'
                   }
                 ],
```

Great, there's the blobId that I want.  Now I need to fetch it.  I need the downloadUrl.  I print the `downloadUrl` from the session and I get this:

```
https://www.fastmailusercontent.com/jmap/download/{accountId}/{blobId}/{name}?type={type}
```

Let's fill that out and GET it… and it works!  The code I end with at my munged copy of top-ten is this:

```perl
my $first_email = $mail_reply->[1][1]{list}[0];
print Dumper($first_email);

my $first_attachment = $first_email->{attachments}[0];

my $blob_id = $first_attachment->{blobId};
my $name = $first_attachment->{name};
my $type = $first_attachment->{type};

my $url = $session->{downloadUrl};

$url =~ s/\{accountId\}/$account_id/g;
$url =~ s/\{blobId\}/$blob_id/g;
$url =~ s/\{name\}/$name/g;
$url =~ s/\{type\}/$type/g;

use Data::Dumper;
print Dumper($url);

my $res = $www->get(
  $url,
  Authorization  => "Bearer $token",
);

print $res->as_string;
```

I hope this answers your questions.  It's basically just [the "downloading" section of RFC 8620](https://www.rfc-editor.org/rfc/rfc8620.html#section-6.2).

I'm closing this issue, but let us know how it goes.
