### ISSUE TITLE
JMAP access to memos feature?

### ISSUE THREAD

**Issue by luckman212** [fastmail/JMAP-Samples#32]
@neilj I read your [announcement about the new memos feature][1] with excitement. 🎉 

I'm wondering if there's any consideration for extending JMAP to support these memos in any way?

Also, regarding this restriction:

> _"Please note, if you have turned conversation grouping off, **you’ll need to turn it back on to use memos**."_

May I ask the reason for this design decision? I don't understand why these two features are codependent.

Thank you 

[1]: https://www.fastmail.com/blog/introducing-memos/

**Comment by rjbs** [comment]
Short version:  Memos are just plaintext emails stored in the memos mailbox. and marked with keywords  (Have a look at the underlying emails and threads and you'll see all this.)  So there isn't much to be done to extend JMAP for this, happily!  We might look to update the keyword registry or mailbox role registry, though.

A memo on message X is represented as an email in reply to message X.  Roughly speaking, conversations mode turns on all the machinery for fetching messages in the same thread, which includes memos.

Neil may want to reply more, but I figured you might appreciate a rough answer during our time zone, instead of waiting for his. 😉

**Comment by luckman212** [comment]
@rjbs Thanks for the quick reply. Okay, that makes some sense. I would love to be able to use this but I strongly dislike conversation mode, so for now that's a blocker.

**Comment by neilj** [comment]
There's no new JMAP features required for memos! They are simply plain-text messages with the keyword `$memo`, that have the same subject as the message the memo is attached to, and an `In-reply-to` header with its message id. Fastmail is detecting this and displaying them differently.

Conversation grouping is required because we have to load the Thread object + the headers of all the messages in the conversation to find any memos attached to a message, and when conversation grouping is turned off we don't fetch this data at all as it's otherwise unneeded.
